### ISSUE TITLE
Anki is not found 

### ISSUE THREAD

**Issue by fzerorubigd** [psamim/kindle2anki#1]
I use virtualenv for clean env and I get this error : 

Traceback (most recent call last):
  File "./kindle2anki.py", line 4, in <module>
    import card_creator
  File "/home/f0rud/funspace/kindle2anki/card_creator.py", line 6, in <module>
    from anki import Collection as aopen
ImportError: No module named 'anki'

**Comment by psamim** [comment]
@fzerorubigd 
Did you init and update the git submodule?
What did you do when you got the error?

**Comment by fzerorubigd** [comment]
Yes. the submodule is at 7c76a23cce923e5c2873e1b32632b3432c952c5a

**Comment by psamim** [comment]
@fzerorubigd I just also created an AUR package for it. It works fine for me. Would you please test it?
https://aur.archlinux.org/packages/kindle2anki-git/

**Comment by dryganets** [comment]
The root cause of the problem is in usage of absolute path in the import statement
you supposed to use a relative path instead

**Comment by psamim** [comment]
@dryganets Oh! Thanks.
Fixed in https://github.com/psamim/kindle2anki/commit/ae649bf0484f22e54d494aadad29d0b61fd9c647
