### ISSUE TITLE
Installation change

### ISSUE THREAD

**Issue by johan456789** [psamim/kindle2anki#2]
The anki submodule url has changed. `anki` can now be installed with pip.

```
pip install anki
pip install retrying
pip install pyperclip
```

Include them in `requirements.txt`?

**Comment by psamim** [comment]
@johan456789 Thanks for noticing! I was surprised and delighted to see someone using this. I updated the requirements and also the AUR package. Please keep me updated if there any issues.

**Comment by johan456789** [comment]
@psamim Thanks for the quick update! I'll report if there's more issues.
